server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;
    root /www/apps/mainweb/app;
    index index.html;

    access_log /www/apps/mainweb/logs/access.log;
    error_log /www/apps/mainweb/logs/error.log;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location = /favicon.svg {
        expires 7d;
        add_header Cache-Control "public";
    }

    location ~* \.(js|css|svg|woff2?)$ {
        expires 7d;
        add_header Cache-Control "public";
        try_files $uri =404;
    }
}
