user www www;
worker_processes auto;
error_log /www/server/nginx/logs/error.log;
pid /www/server/nginx/logs/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include mime.types;
    default_type application/octet-stream;
    sendfile on;
    keepalive_timeout 65;
    server_tokens off;
    client_max_body_size 50m;
    gzip on;
    gzip_min_length 1024;
    gzip_types text/plain text/css application/javascript application/json image/svg+xml;

    lua_package_path "/www/server/nginx/lib/lua/?.lua;;";

    include /www/server/panel/vhost/nginx/*.conf;
}
